images:
  - image: "boredazfcuk/icloudpd"
    tag: "1.0.1282_20-08-2025"
    name: "icloudpd"
  - image: "nextcloud"
    tag: "31.0.5-apache"
    name: "nextcloud"
  - image: "vaultwarden/server"
    tag: "1.34.3"
    name: "vaultwarden"
  - image: "redis"
    tag: "7.4.5"
    name: "redis"
  - image: "nacos/nacos-server"
    tag: "v2.5.1"
    name: "nacos-server"
  - image: "nacos/nacos-server"
    tag: "v3.0.3"
    name: "nacos-server"
  - image: "mysql"
    tag: "8.0.43"
    name: "mysql"
  - image: "bitnami/postgresql"
    tag: "17.6.0"
    name: "postgresql"
  - image: "minio/minio"
    tag: "RELEASE.2025-04-22T22-12-26Z"
    name: "minio"
  - image: "apache/rocketmq"
    tag: "5.3.3"
    name: "rocketmq"
  - image: "apacherocketmq/rocketmq-dashboard"
    tag: "2.0.1"
    name: "rocketmq-dashboard"