images:
  # Immich 照片管理套件 (Immich Photo Suite)
  - registry: "ghcr.io"
    image: "immich-app/immich-server"
    tag: "v1.140.1"
    name: "immich-server"

  - registry: "ghcr.io"
    image: "immich-app/immich-machine-learning"
    tag: "v1.140.1"
    name: "immich-machine-learning"

  - registry: "ghcr.io"
    image: "immich-app/postgres"
    tag: "17-vectorchord0.4.3-pgvectors0.3.0"
    name: "immich-postgres"

  - registry: "docker.io"
    image: "valkey/valkey"
    tag: "8-bookworm"
    name: "valkey"

  # 数据备份与同步 (Data Backup & Sync)
  - registry: "docker.io"
    image: "boredazfcuk/icloudpd"
    tag: "1.0.1282_20-08-2025"
    name: "icloudpd"

  - registry: "docker.io"
    image: "linuxserver/duplicati"
    tag: "2.1.0"
    name: "duplicati"

  # 个人云与密码管理 (Personal Cloud & Password Manager)
  - registry: "docker.io"
    image: "nextcloud"
    tag: "31.0.5-apache"
    name: "nextcloud"

  - registry: "docker.io"
    image: "vaultwarden/server"
    tag: "1.34.3-alpine"
    name: "vaultwarden"

  # 通用数据库 (General Databases)
  - registry: "docker.io"
    image: "redis"
    tag: "7.4.5"
    name: "redis"

  - registry: "docker.io"
    image: "mysql"
    tag: "8.0.43"
    name: "mysql"

  - registry: "docker.io"
    image: "bitnami/postgresql"
    tag: "17.6.0"
    name: "postgresql"

  # 中间件与开发运维 (Middleware & DevOps)
  - registry: "docker.io"
    image: "nacos/nacos-server"
    tag: "v2.5.1"
    name: "nacos-server"

  - registry: "docker.io"
    image: "nacos/nacos-server"
    tag: "v3.0.3"
    name: "nacos-server"

  - registry: "docker.io"
    image: "minio/minio"
    tag: "RELEASE.2025-04-22T22-12-26Z"
    name: "minio"

  - registry: "docker.io"
    image: "apache/rocketmq"
    tag: "5.3.3"
    name: "rocketmq"

  - registry: "docker.io"
    image: "apacherocketmq/rocketmq-dashboard"
    tag: "2.0.1"
    name: "rocketmq-dashboard"

  - registry: "code.forgejo.org"
    image: "forgejo/forgejo"
    tag: "12.0.1"
    name: "forgejo"